### PR TITLE
Throw more clear errors in Keypair init and sign

### PR DESCRIPTION
**Pull request by aliciawyy**
Together with some small refactoring the the class Keypair and StellarMnemonic.

### CODE REVIEW

**Comment by aliciawyy** [comment]
Hi @overcat Maybe enable travis on this branch as well and add a coverage check like [codecov](https://codecov.io/gh) ?

**Comment by overcat** [comment]
Thank you for your contribution. Code style checking will be added later. :-）

**Comment by aliciawyy** [comment]
Hi @overcat, you are welcome. The code idea is nice, I'd be happy to help :)
By the way, why not merge the v0.2 branch into master or dev to be the base branch ?

**Comment by overcat** [comment]
@aliciawyy I want to merge the v0.2 branch into the master branch after the new version is released.

**Comment by aliciawyy** [comment]
Ok. So now the working branch is v0.2 or dev ?

**Comment by overcat** [comment]
@aliciawyy dev.

**Comment by aliciawyy** [comment]
@overcat Ok :)

**Pull request merged**
