### PR TITLE
Change for public network

### PR DESCRIPTION
**Pull request by kaotisk-hund**
According to https://github.com/StellarCN/py-stellar-base/issues/534
#534

### CODE REVIEW

**Comment by overcat** [comment]
Thank you for your PR, but in order to avoid unnecessary risks, I prefer to connect to the test network in the code, we can indicate how to connect to the public network in the code comments, do you think so?

**Comment by kaotisk-hund** [comment]
I can agree. I understand the risk avoidance, though it may need to reformat the documentation instead of the example.

**Comment by overcat** [comment]
Okay, I will fix it later.

**Comment by kaotisk-hund** [comment]
I made this if you approve or is properly written :smile:

**Pull request merged**
