### PR TITLE
Edit travis for nosetests

### PR DESCRIPTION
**Pull request by Akuukis**
Tested and working properly.

### CODE REVIEW

**Comment by HongxuChen** [comment]
@Akuukis Thanks. But I have some questions.

- What do you mean by saying "tested and working properly"?
- Why nose instead of py.test?
- It's better to use [contain-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure), right?
- Why explicitly turn off email notifications?
- irc is not necessary, at least presently; I don't think it is mature enough to open up a channel on freenode.

Additionally, I think using unittest is fine and can be integrated into py.test. Using vanilla `assert` may not be a good idea.

**Comment by Akuukis** [comment]
@HongxuChen ,

1. I mean't that Travis parses config and run tests as intended.
2. I use also nose for project that depends on `py-stellar-base`, and at first I wrote tests for `py-stellar-base` from within my project. But py.test could be better, haven't used it. As we have travis doing the test there's no reason to choose nose anymore from my point of view.
3. Yes, and by default travis does contain-based infrastructure. 
4. I thought about IRC because we are already 3-5 people actively contributing to project and so everyone could be notified.

Feel free to correct me, all of that is my opinion because I am still learning python.

**Comment by HongxuChen** [comment]
@Akuukis 

Actually I don't care whether using nose or pytest, but I do hope the unit test framework to be unified  and remain unchanged. But currently the top priority should be eliminating test failures; so let's put aside this. As to `assert`, I prefer use it for pre-condition, and py.test/nose for unit test. 

Yes, travis seems defaulting to contained-based; the explicit `sudo: false` works just like a hint that travis won't use admin privilege. AFAIK, `python setup.py install` may write to protected directories like `/usr/local/`.

For notifications, GitHub has already had private feeds for activities of followed people and watching repositories.

**Comment by Akuukis** [comment]
@HongxuChen 
Also in [this](http://stackoverflow.com/a/2958450/4817809) answer it makes a good point not to use `assert` in unit tests because of `python -O` flag. So lets stick to `unittest` in unit tests.

As of priorities I have little understanding of code where errors happen, so I will keep making tests and I can rewrite the unit test framework along the way.

For Travis I checked out the console output and it writes only to local directories, like `/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/base58-0.2.2-py3.4.egg` and similar. But yes, hints are good.

**Comment by HongxuChen** [comment]
@Akuukis Thanks that you will contribute to it.

Sorry I don't know about these errors. But hope you will help to clear them!

Good to know that travis uses virtualenv.

**Pull request merged**
