### PR TITLE
fix: the wordlist should be included

### PR DESCRIPTION
**Pull request by overcat**
#58

### CODE REVIEW

**Comment by kfiresmith** [comment]
Please also include the english and japanese wordlists I provided in pull #59.  So:
`+include stellar_base/wordlist/english.txt 
+include stellar_base/wordlist/japanese.txt 
`
Thank you!

**Comment by overcat** [comment]
I do not think they should be included here, they should be handled by mnemonic.

**Comment by kfiresmith** [comment]
The official Python mnemonic?  I'm not sure how to make that work.  Even with Python Mnemonic installed, using current Python 3.6, we get a traceback for a missing wordlist inside stellar_base for english, until I manually copy the file over by hand from site_packages/mnemonic to stellar_base/wordlists/english.txt (paths approximate from memory)

**Comment by overcat** [comment]
Have you tried the code with this pull request? You can get it from here: https://github.com/overcat/py-stellar-base , I test it on Python 2.7 and 3.6.3, it works for me.
```
(py-stellar) ➜  Python git clone https://github.com/overcat/py-stellar-base.git
Cloning into 'py-stellar-base'...
remote: Counting objects: 669, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 669 (delta 18), reused 27 (delta 13), pack-reused 629
Receiving objects: 100% (669/669), 236.90 KiB | 56.00 KiB/s, done.
Resolving deltas: 100% (413/413), done.
Checking connectivity... done.
(py-stellar) ➜  Python pip install ./py-stellar-base 
Processing ./py-stellar-base
...
Successfully installed SSEClient-0.0.18 certifi-2017.11.5 chardet-3.0.4 crc16-0.1.1 ed25519-1.4 idna-2.6 mnemonic-0.18 numpy-1.13.3 pbkdf2-1.3 requests-2.18.4 six-1.11.0 stellar-base-0.1.0 toml-0.9.4 urllib3-1.22
(py-stellar) ➜  Python python
Python 3.6.3 (default, Dec  5 2017, 22:54:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stellar_base.utils import StellarMnemonic
>>> sm = StellarMnemonic()
>>> m = sm.generate() 
>>> m
'worry opera catalog aisle cereal honey course ride glory top satoshi rigid'
>>> sm = StellarMnemonic('chinese')
>>> m = sm.generate() 
>>> m
'泡 曾 治 深 遵 标 页 弟 尺 诸 最 冯'
>>> 
```

**Comment by kfiresmith** [comment]
This merge works!  Thanks again @overcat!

**Comment by kfiresmith** [comment]
I was able to get in touch with the Pypi module maintainer for the pip (/u/antb123) and he said that he'd repackage the latest version of master once we've gotten this merged provided that "there is good test coverage".  

I've tested the minor changes in this pull request but I'm not sure how well everything else that's been updated since 2016-10-30.

**Comment by overcat** [comment]
@kfiresmith Thanks for your contribution, but the commit has not been reviewed, and I think my code should not be merged by myself.  I will give you more information once I get more updates.

Thanks again.

**Comment by manran** [comment]
There is a [SEP-0005](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md)  working for similar usage. I suggest that working with it instead of continue working on this. @overcat  @kfiresmith

**Comment by kfiresmith** [comment]
@manran  - that makes sense in the long term, but the work here is minor and already complete.  If this could be merged in the mean time, we would have a working solution until SEP-0005 is ready.

There is an immediate need for this functionality and I hate to point people toward an unmerged-but-working branch to meet it while we wait for SEP-0005.  Merging this would also allow the PIP in Pypi.org to be updated with code that matches what the current documentation (readme.md) asserts with regard to functionality.

Thanks!

**Comment by manran** [comment]
@kfiresmith I think you are right.

**Comment by overcat** [comment]
@kfiresmith I prepared a version([v0.1.6](https://github.com/StellarCN/py-stellar-base/tree/0.1.6)) that can be uploaded to pypi. Thank you.

**Comment by kfiresmith** [comment]
Beautiful - thanks @overcat & @manran !

**Comment by overcat** [comment]
@kfiresmith I am very grateful to you for your help and hope to  have more discussions with you in the future.

**Pull request merged**
